export const mockInvoices = [
    {
        id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
        client_id: 'client-001-uuid-here',
        project_id: 'project-001-uuid-here',
        invoice_number: 'INV-2024-001',
        title: 'Website Development - Phase 1',
        amount: 5000.00,
        deposit_percentage: 30,
        deposit_amount: 1500.00,
        status: 'pending',
        due_date: '2024-11-15',
        paid_at: null,
        payment_method: null,
        notes: 'Initial development phase including design mockups',
        created_at: '2024-10-01T10:00:00Z',
        updated_at: '2024-10-01T10:00:00Z',
    },
    {
        id: 'b2c3d4e5-f6g7-8901-bcde-f12345678901',
        client_id: 'client-001-uuid-here',
        project_id: 'project-002-uuid-here',
        invoice_number: 'INV-2024-002',
        title: 'Mobile App Development',
        amount: 12000.00,
        deposit_percentage: 50,
        deposit_amount: 6000.00,
        status: 'paid',
        due_date: '2024-10-20',
        paid_at: '2024-10-18T14:30:00Z',
        payment_method: 'credit_card',
        notes: 'iOS and Android app development',
        created_at: '2024-09-15T09:00:00Z',
        updated_at: '2024-10-18T14:30:00Z',
    },
    {
        id: 'c3d4e5f6-g7h8-9012-cdef-123456789012',
        client_id: 'client-001-uuid-here',
        project_id: 'project-003-uuid-here',
        invoice_number: 'INV-2024-003',
        title: 'E-commerce Integration',
        amount: 3500.00,
        deposit_percentage: 25,
        deposit_amount: 875.00,
        status: 'overdue',
        due_date: '2024-10-10',
        paid_at: null,
        payment_method: null,
        notes: 'Payment gateway and shopping cart setup',
        created_at: '2024-09-20T11:00:00Z',
        updated_at: '2024-09-20T11:00:00Z',
    },
    {
        id: 'd4e5f6g7-h8i9-0123-defg-234567890123',
        client_id: 'client-001-uuid-here',
        project_id: 'project-004-uuid-here',
        invoice_number: 'INV-2024-004',
        title: 'SEO Optimization Services',
        amount: 2500.00,
        deposit_percentage: 0,
        deposit_amount: 0.00,
        status: 'draft',
        due_date: '2024-11-30',
        paid_at: null,
        payment_method: null,
        notes: 'Monthly SEO package - 3 months',
        created_at: '2024-10-15T13:00:00Z',
        updated_at: '2024-10-15T13:00:00Z',
    },
    {
        id: 'e5f6g7h8-i9j0-1234-efgh-345678901234',
        client_id: 'client-001-uuid-here',
        project_id: 'project-005-uuid-here',
        invoice_number: 'INV-2024-005',
        title: 'Cloud Migration Services',
        amount: 8500.00,
        deposit_percentage: 40,
        deposit_amount: 3400.00,
        status: 'pending',
        due_date: '2024-11-05',
        paid_at: null,
        payment_method: null,
        notes: 'AWS infrastructure setup and migration',
        created_at: '2024-10-05T15:00:00Z',
        updated_at: '2024-10-05T15:00:00Z',
    },
]
export const mockServices = [
    // Design Services
    {
        id: 'service-001-uuid-here',
        name: 'Logo Design',
        description: 'Professional logo design with multiple concepts, revisions, and brand guidelines. Delivered in all formats (AI, PNG, SVG, PDF).',
        category: 'design',
        base_price: 1500.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-002-uuid-here',
        name: 'UI/UX Design',
        description: 'Complete user interface and experience design for web and mobile applications. Includes wireframes, mockups, and interactive prototypes.',
        category: 'design',
        base_price: 3500.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-003-uuid-here',
        name: 'Brand Identity Package',
        description: 'Comprehensive brand identity including logo, color palette, typography, business cards, letterhead, and brand guidelines.',
        category: 'design',
        base_price: 4500.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },

    // Development Services
    {
        id: 'service-004-uuid-here',
        name: 'Website Development',
        description: 'Custom website development with responsive design, CMS integration, and modern technologies. Includes hosting setup and deployment.',
        category: 'development',
        base_price: 5000.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-005-uuid-here',
        name: 'Mobile App Development',
        description: 'Native iOS and Android mobile application development with cross-platform compatibility and app store deployment.',
        category: 'development',
        base_price: 15000.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-006-uuid-here',
        name: 'E-commerce Development',
        description: 'Full-featured e-commerce platform with product management, payment processing, inventory tracking, and order fulfillment.',
        category: 'development',
        base_price: 8500.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-007-uuid-here',
        name: 'API Development',
        description: 'RESTful API development with documentation, authentication, rate limiting, and comprehensive testing.',
        category: 'development',
        base_price: 4000.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },

    // SEO Services
    {
        id: 'service-008-uuid-here',
        name: 'SEO Audit',
        description: 'Comprehensive SEO audit including technical analysis, content review, backlink profile, and actionable recommendations.',
        category: 'seo',
        base_price: 1200.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-009-uuid-here',
        name: 'Monthly SEO Package',
        description: 'Ongoing SEO services including keyword research, on-page optimization, content strategy, and monthly reporting.',
        category: 'seo',
        base_price: 2000.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-010-uuid-here',
        name: 'Local SEO',
        description: 'Local search optimization for businesses targeting specific geographic areas. Includes Google My Business optimization.',
        category: 'seo',
        base_price: 1500.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },

    // Marketing Services
    {
        id: 'service-011-uuid-here',
        name: 'Social Media Management',
        description: 'Complete social media management including content creation, scheduling, community engagement, and analytics.',
        category: 'marketing',
        base_price: 2500.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-012-uuid-here',
        name: 'Email Marketing Campaign',
        description: 'Email marketing campaign design and execution including template design, list management, and performance tracking.',
        category: 'marketing',
        base_price: 1800.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-013-uuid-here',
        name: 'Content Marketing Strategy',
        description: 'Strategic content marketing plan including content calendar, blog posts, infographics, and distribution strategy.',
        category: 'marketing',
        base_price: 3000.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-014-uuid-here',
        name: 'PPC Campaign Management',
        description: 'Pay-per-click advertising campaign management for Google Ads, Facebook Ads, and other platforms.',
        category: 'marketing',
        base_price: 2200.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },

    // Support Services
    {
        id: 'service-015-uuid-here',
        name: 'Website Maintenance',
        description: 'Monthly website maintenance including updates, backups, security monitoring, and technical support.',
        category: 'support',
        base_price: 500.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-016-uuid-here',
        name: 'Technical Support Package',
        description: 'Dedicated technical support with priority response times, bug fixes, and troubleshooting assistance.',
        category: 'support',
        base_price: 1000.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'service-017-uuid-here',
        name: 'Cloud Infrastructure Management',
        description: 'Ongoing cloud infrastructure management including server monitoring, scaling, security, and optimization.',
        category: 'support',
        base_price: 1500.00,
        is_active: true,
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
    },
];

export const mockProjects = [
    {
        id: 'project-001-uuid-here',
        client_id: 'client-001-uuid-here',
        name: 'Corporate Website Redesign',
        description: 'Complete redesign of corporate website with modern UI/UX, responsive design, and improved user experience. Includes homepage, about, services, and contact pages.',
        status: 'in_progress',
        progress_percentage: 65,
        start_date: '2024-09-01',
        end_date: '2024-12-15',
        created_at: '2024-09-01T10:00:00Z',
        updated_at: '2024-10-20T14:30:00Z',
    },
    {
        id: 'project-002-uuid-here',
        client_id: 'client-001-uuid-here',
        name: 'Mobile App Development',
        description: 'Native iOS and Android mobile application for customer engagement with push notifications, in-app messaging, and analytics dashboard.',
        status: 'completed',
        progress_percentage: 100,
        start_date: '2024-08-15',
        end_date: '2024-10-30',
        created_at: '2024-08-15T09:00:00Z',
        updated_at: '2024-10-30T16:00:00Z',
    },
    {
        id: 'project-003-uuid-here',
        client_id: 'client-001-uuid-here',
        name: 'E-commerce Platform',
        description: 'Full-featured e-commerce platform with product catalog, shopping cart, payment processing, order management, and customer portal.',
        status: 'in_progress',
        progress_percentage: 45,
        start_date: '2024-09-20',
        end_date: '2025-01-30',
        created_at: '2024-09-20T11:00:00Z',
        updated_at: '2024-10-25T09:15:00Z',
    },
    {
        id: 'project-004-uuid-here',
        client_id: 'client-001-uuid-here',
        name: 'Marketing Campaign',
        description: 'Digital marketing campaign including social media strategy, content creation, email marketing, and performance analytics.',
        status: 'planning',
        progress_percentage: 20,
        start_date: '2024-10-10',
        end_date: '2024-12-31',
        created_at: '2024-10-10T13:00:00Z',
        updated_at: '2024-10-15T11:00:00Z',
    },
    {
        id: 'project-005-uuid-here',
        client_id: 'client-001-uuid-here',
        name: 'Cloud Infrastructure Migration',
        description: 'Migration of existing infrastructure to AWS cloud with load balancing, auto-scaling, and disaster recovery setup.',
        status: 'on_hold',
        progress_percentage: 30,
        start_date: '2024-09-05',
        end_date: '2024-11-30',
        created_at: '2024-09-05T08:00:00Z',
        updated_at: '2024-10-01T10:30:00Z',
    },
    {
        id: 'project-006-uuid-here',
        client_id: 'client-001-uuid-here',
        name: 'Cloud Infrastructure Migration',
        description: 'Migration of existing infrastructure to AWS cloud with load balancing, auto-scaling, and disaster recovery setup.',
        status: 'on_hold',
        progress_percentage: 20,
        start_date: '2024-09-04',
        end_date: '2024-12-30',
        created_at: '2024-09-05T08:00:00Z',
        updated_at: '2024-10-01T10:30:00Z',
    },
];

export const mockProjectTasks = [
    // Tasks for project-001 (Corporate Website Redesign)
    {
        id: 'task-001-uuid-here',
        project_id: 'project-001-uuid-here',
        title: 'Design Homepage Mockup',
        description: 'Create high-fidelity mockups for the homepage including hero section, features, and call-to-action areas.',
        status: 'completed',
        assigned_to: 'Design Team',
        due_date: '2024-09-15',
        created_at: '2024-09-01T10:00:00Z',
        updated_at: '2024-09-14T16:00:00Z',
    },
    {
        id: 'task-002-uuid-here',
        project_id: 'project-001-uuid-here',
        title: 'Develop Responsive Layout',
        description: 'Implement responsive CSS framework and ensure mobile compatibility across all devices.',
        status: 'in_progress',
        assigned_to: 'Frontend Team',
        due_date: '2024-11-01',
        created_at: '2024-09-16T09:00:00Z',
        updated_at: '2024-10-20T11:30:00Z',
    },
    {
        id: 'task-003-uuid-here',
        project_id: 'project-001-uuid-here',
        title: 'Content Migration',
        description: 'Migrate existing content from old website to new platform and optimize for SEO.',
        status: 'pending',
        assigned_to: 'Content Team',
        due_date: '2024-11-15',
        created_at: '2024-10-01T08:00:00Z',
        updated_at: '2024-10-01T08:00:00Z',
    },
    {
        id: 'task-004-uuid-here',
        project_id: 'project-001-uuid-here',
        title: 'User Testing & QA',
        description: 'Conduct user testing sessions and quality assurance checks before launch.',
        status: 'pending',
        assigned_to: 'QA Team',
        due_date: '2024-12-01',
        created_at: '2024-10-15T10:00:00Z',
        updated_at: '2024-10-15T10:00:00Z',
    },

    // Tasks for project-002 (Mobile App Development)
    {
        id: 'task-005-uuid-here',
        project_id: 'project-002-uuid-here',
        title: 'iOS App Development',
        description: 'Develop native iOS application using Swift with all core features.',
        status: 'completed',
        assigned_to: 'iOS Team',
        due_date: '2024-10-15',
        created_at: '2024-08-15T09:00:00Z',
        updated_at: '2024-10-14T17:00:00Z',
    },
    {
        id: 'task-006-uuid-here',
        project_id: 'project-002-uuid-here',
        title: 'Android App Development',
        description: 'Develop native Android application using Kotlin with feature parity to iOS.',
        status: 'completed',
        assigned_to: 'Android Team',
        due_date: '2024-10-20',
        created_at: '2024-08-15T09:00:00Z',
        updated_at: '2024-10-18T16:30:00Z',
    },
    {
        id: 'task-007-uuid-here',
        project_id: 'project-002-uuid-here',
        title: 'App Store Submission',
        description: 'Prepare and submit applications to Apple App Store and Google Play Store.',
        status: 'completed',
        assigned_to: 'Release Team',
        due_date: '2024-10-25',
        created_at: '2024-10-19T10:00:00Z',
        updated_at: '2024-10-24T14:00:00Z',
    },

    // Tasks for project-003 (E-commerce Platform)
    {
        id: 'task-008-uuid-here',
        project_id: 'project-003-uuid-here',
        title: 'Database Schema Design',
        description: 'Design database schema for products, orders, customers, and inventory management.',
        status: 'completed',
        assigned_to: 'Backend Team',
        due_date: '2024-10-05',
        created_at: '2024-09-20T11:00:00Z',
        updated_at: '2024-10-04T15:00:00Z',
    },
    {
        id: 'task-009-uuid-here',
        project_id: 'project-003-uuid-here',
        title: 'Payment Gateway Integration',
        description: 'Integrate Stripe payment processing with secure checkout flow.',
        status: 'in_progress',
        assigned_to: 'Backend Team',
        due_date: '2024-11-10',
        created_at: '2024-10-10T09:00:00Z',
        updated_at: '2024-10-25T13:30:00Z',
    },
    {
        id: 'task-010-uuid-here',
        project_id: 'project-003-uuid-here',
        title: 'Product Catalog UI',
        description: 'Build product listing pages with filtering, sorting, and search functionality.',
        status: 'in_progress',
        assigned_to: 'Frontend Team',
        due_date: '2024-11-20',
        created_at: '2024-10-15T08:00:00Z',
        updated_at: '2024-10-26T10:00:00Z',
    },
    {
        id: 'task-011-uuid-here',
        project_id: 'project-003-uuid-here',
        title: 'Admin Dashboard',
        description: 'Create admin dashboard for managing products, orders, and customers.',
        status: 'pending',
        assigned_to: 'Full Stack Team',
        due_date: '2024-12-15',
        created_at: '2024-10-20T11:00:00Z',
        updated_at: '2024-10-20T11:00:00Z',
    },

    // Tasks for project-004 (Marketing Campaign)
    {
        id: 'task-012-uuid-here',
        project_id: 'project-004-uuid-here',
        title: 'Market Research',
        description: 'Conduct market research and competitor analysis for campaign strategy.',
        status: 'completed',
        assigned_to: 'Marketing Team',
        due_date: '2024-10-20',
        created_at: '2024-10-10T13:00:00Z',
        updated_at: '2024-10-19T16:00:00Z',
    },
    {
        id: 'task-013-uuid-here',
        project_id: 'project-004-uuid-here',
        title: 'Content Calendar',
        description: 'Develop 3-month content calendar for social media and email campaigns.',
        status: 'in_progress',
        assigned_to: 'Content Team',
        due_date: '2024-11-05',
        created_at: '2024-10-21T09:00:00Z',
        updated_at: '2024-10-25T14:30:00Z',
    },
    {
        id: 'task-014-uuid-here',
        project_id: 'project-004-uuid-here',
        title: 'Campaign Launch',
        description: 'Execute campaign launch across all channels with monitoring and optimization.',
        status: 'pending',
        assigned_to: 'Marketing Team',
        due_date: '2024-12-01',
        created_at: '2024-10-22T10:00:00Z',
        updated_at: '2024-10-22T10:00:00Z',
    },

    // Tasks for project-005 (Cloud Infrastructure Migration)
    {
        id: 'task-015-uuid-here',
        project_id: 'project-005-uuid-here',
        title: 'Infrastructure Audit',
        description: 'Audit current infrastructure and create migration plan.',
        status: 'completed',
        assigned_to: 'DevOps Team',
        due_date: '2024-09-20',
        created_at: '2024-09-05T08:00:00Z',
        updated_at: '2024-09-19T17:00:00Z',
    },
    {
        id: 'task-016-uuid-here',
        project_id: 'project-005-uuid-here',
        title: 'AWS Environment Setup',
        description: 'Set up AWS environment with VPC, security groups, and IAM roles.',
        status: 'completed',
        assigned_to: 'DevOps Team',
        due_date: '2024-09-30',
        created_at: '2024-09-21T09:00:00Z',
        updated_at: '2024-09-29T15:00:00Z',
    },
    {
        id: 'task-017-uuid-here',
        project_id: 'project-005-uuid-here',
        title: 'Data Migration',
        description: 'Migrate databases and application data to AWS cloud.',
        status: 'on_hold',
        assigned_to: 'DevOps Team',
        due_date: '2024-11-15',
        created_at: '2024-10-01T10:00:00Z',
        updated_at: '2024-10-01T10:30:00Z',
    },
];

export const mockQuotes = [
    {
        id: 'quote-001-uuid-here',
        client_id: 'client-001-uuid-here',
        service_id: 'service-001-uuid-here',
        quote_number: 'QT-2024-001',
        title: 'Custom CRM Development',
        description: 'Complete CRM system with lead tracking, contact management, sales pipeline, and reporting dashboard. Includes mobile responsive design and API integration capabilities.',
        amount: 15000.00,
        status: 'pending',
        valid_until: '2024-11-30',
        notes: 'Includes 3 months of post-launch support and training for up to 10 users.',
        created_at: '2024-10-20T10:00:00Z',
        updated_at: '2024-10-20T10:00:00Z',
    },
    {
        id: 'quote-002-uuid-here',
        client_id: 'client-001-uuid-here',
        service_id: 'service-002-uuid-here',
        quote_number: 'QT-2024-002',
        title: 'Website Maintenance Package',
        description: 'Annual website maintenance including monthly updates, security patches, backup management, performance optimization, and 24/7 monitoring.',
        amount: 1200.00,
        status: 'accepted',
        valid_until: '2024-11-15',
        notes: 'Billed quarterly. Emergency support available with 4-hour response time.',
        created_at: '2024-10-15T14:00:00Z',
        updated_at: '2024-10-16T09:30:00Z',
    },
    {
        id: 'quote-003-uuid-here',
        client_id: 'client-001-uuid-here',
        service_id: 'service-003-uuid-here',
        quote_number: 'QT-2024-003',
        title: 'Brand Identity Design',
        description: 'Complete brand identity package including logo design, color palette, typography system, brand guidelines, business card design, and letterhead templates.',
        amount: 4500.00,
        status: 'pending',
        valid_until: '2024-12-01',
        notes: 'Includes up to 3 revision rounds. Additional revisions at $150/hour.',
        created_at: '2024-10-18T11:00:00Z',
        updated_at: '2024-10-18T11:00:00Z',
    },
    {
        id: 'quote-004-uuid-here',
        client_id: 'client-001-uuid-here',
        service_id: 'service-004-uuid-here',
        quote_number: 'QT-2024-004',
        title: 'E-commerce Platform Development',
        description: 'Full-featured e-commerce platform with product catalog, shopping cart, payment gateway integration, inventory management, and admin dashboard.',
        amount: 22000.00,
        status: 'rejected',
        valid_until: '2024-10-25',
        notes: 'Quote expired. Client requested revised proposal with phased approach.',
        created_at: '2024-09-20T08:00:00Z',
        updated_at: '2024-10-22T16:45:00Z',
    },
    {
        id: 'quote-005-uuid-here',
        client_id: 'client-001-uuid-here',
        service_id: 'service-005-uuid-here',
        quote_number: 'QT-2024-005',
        title: 'Mobile App Design & Prototype',
        description: 'UI/UX design for iOS and Android mobile application including user research, wireframes, high-fidelity mockups, and interactive prototype.',
        amount: 8500.00,
        status: 'pending',
        valid_until: '2024-11-20',
        notes: 'Design files delivered in Figma. Includes design system and component library.',
        created_at: '2024-10-22T13:00:00Z',
        updated_at: '2024-10-22T13:00:00Z',
    },
    {
        id: 'quote-006-uuid-here',
        client_id: 'client-001-uuid-here',
        service_id: 'service-006-uuid-here',
        quote_number: 'QT-2024-006',
        title: 'SEO Optimization & Content Strategy',
        description: 'Comprehensive SEO audit, keyword research, on-page optimization, content strategy development, and 6 months of ongoing SEO support.',
        amount: 6800.00,
        status: 'accepted',
        valid_until: '2024-11-10',
        notes: 'Monthly reporting included. Content writing services available as add-on.',
        created_at: '2024-10-10T10:30:00Z',
        updated_at: '2024-10-12T14:20:00Z',
    },
];

// @/lib/mockData.ts

export const mockTickets = [
    {
        id: '1',
        ticket_number: 'TK-1001',
        subject: 'Login not working',
        category: 'technique',
        priority: 'high',
        status: 'open',
        created_at: new Date('2025-10-20T10:00:00').toISOString(),
    },
    {
        id: '2',
        ticket_number: 'TK-1002',
        subject: 'Billing discrepancy',
        category: 'facturation',
        priority: 'medium',
        status: 'open',
        created_at: new Date('2025-10-21T12:30:00').toISOString(),
    },
    {
        id: '3',
        ticket_number: 'TK-1003',
        subject: 'Feature request: Dark mode',
        category: 'service',
        priority: 'low',
        status: 'closed',
        created_at: new Date('2025-10-22T09:15:00').toISOString(),
    },
    {
        id: '4',
        ticket_number: 'TK-1004',
        subject: 'Unable to upload files',
        category: 'technique',
        priority: 'urgent',
        status: 'open',
        created_at: new Date('2025-10-23T14:45:00').toISOString(),
    },
    {
        id: '5',
        ticket_number: 'TK-1005',
        subject: 'Account deletion request',
        category: 'service',
        priority: 'medium',
        status: 'closed',
        created_at: new Date('2025-10-24T11:20:00').toISOString(),
    },
];

export const mockMessages = [
    { id: 'm1', ticketId: '1', message: 'I cannot log in.', is_staff: false, created_at: new Date('2025-10-20T10:05:00').toISOString() },
    { id: 'm2', ticketId: '1', message: 'Have you tried resetting your password?', is_staff: true, created_at: new Date('2025-10-20T10:10:00').toISOString() },
    { id: 'm3', ticketId: '2', message: 'My last invoice seems wrong.', is_staff: false, created_at: new Date('2025-10-21T12:35:00').toISOString() },
    { id: 'm4', ticketId: '2', message: 'We are checking your invoice, will update soon.', is_staff: true, created_at: new Date('2025-10-21T12:40:00').toISOString() },
    { id: 'm5', ticketId: '3', message: 'Would love to have dark mode.', is_staff: false, created_at: new Date('2025-10-22T09:20:00').toISOString() },
    { id: 'm6', ticketId: '4', message: 'Cannot upload any PDF files.', is_staff: false, created_at: new Date('2025-10-23T14:50:00').toISOString() },
    { id: 'm7', ticketId: '4', message: 'We fixed the upload issue, try again.', is_staff: true, created_at: new Date('2025-10-23T15:00:00').toISOString() },
    { id: 'm8', ticketId: '5', message: 'Please delete my account.', is_staff: false, created_at: new Date('2025-10-24T11:25:00').toISOString() },
    { id: 'm9', ticketId: '5', message: 'Your account has been deleted successfully.', is_staff: true, created_at: new Date('2025-10-24T11:30:00').toISOString() },
];

export const mockOfferData = [
    {
        id: "1",
        title: "20% Off Web Design Packages",
        description: "Get 20% off all web design services for the next month!",
        expiresAt: "2025-12-15",
        category: "Web Design",
        audience: "All Clients",
        imageUrl: "/images/web-design.jpg",
    },
    {
        id: "2",
        title: "Free Consultation",
        description: "Book a free 30-minute consultation with our experts.",
        category: "Consultation",
        audience: "New Clients",
        imageUrl: "/images/consultation.jpg",
    },
    {
        id: "3",
        title: "SEO Audit Discount",
        description: "Get a 50% discount on your first SEO audit.",
        expiresAt: "2025-11-30",
        category: "SEO",
        audience: "All Clients",
        imageUrl: "/images/seo.jpg",
    },
    {
        id: "4",
        title: "Social Media Package Offer",
        description: "Sign up for a social media package and get 1 extra month free.",
        category: "Marketing",
        audience: "All Clients",
        expiresAt: "2025-12-31",
        imageUrl: "/images/social-media.jpg",
    },
    {
        id: "5",
        title: "Referral Bonus",
        description: "Refer a friend and both of you get 10% off your next project.",
        category: "Referral",
        audience: "Existing Clients",
    },
];
export const mockPayments = [
    {
        payment_id: "PAY-001",
        client_name: "John Doe",
        project_name: "Website Redesign",
        invoice_id: "INV-101",
        paid_at: "2025-10-28",
        due_date: "2025-10-28", // paid on time
        amount: 1200,
        deposit_amount: 300,
        deposit_percentage: 25,
        payment_method: "Credit Card",
        status: "paid",
    },
    {
        payment_id: "PAY-002",
        client_name: "Acme Corp",
        project_name: "Mobile App",
        invoice_id: "INV-102",
        paid_at: null, // not paid yet
        due_date: "2025-5-30",
        amount: 5000,
        deposit_amount: 1000,
        deposit_percentage: 20,
        payment_method: "Bank Transfer",
        status: "overdue",
    },
    {
        payment_id: "PAY-003",
        client_name: "Jane Smith",
        project_name: "Marketing Campaign",
        invoice_id: "INV-103",
        paid_at: null,
        due_date: "2025-10-27",
        amount: 2000,
        deposit_amount: 500,
        deposit_percentage: 25,
        payment_method: "PayPal",
        status: "overdue",
    },
];


export const mockUsers = [
    {
        user_id: "U-001",
        full_name: "Ahmed Ben Ali",
        email: "ahmed@techify.com",
        company: "Techify",
        address: "123 Main St",
        phone: "+212 600 123 456",
        city: "Casablanca",
        country: "Morocco",
        client_type: "Company",
        currency: "MAD",
        siren: "987654321",
        vat: "MA123456789",
        ice: "0012345670001",
    },
    {
        user_id: "U-002",
        full_name: "Sara El Fassi",
        email: "sara@devspark.com",
        company: "-",
        address: "45 Agdal Blvd",
        phone: "+212 661 789 012",
        city: "Rabat",
        country: "Morocco",
        client_type: "Individual",
        currency: "USD",
        siren: "123456789",
        vat: "MA987654321",
        ice: "0098765432100",
    },
    {
        user_id: "U-003",
        full_name: "Youssef Lahlou",
        email: "youssef@atlaswebstudio.com",
        company: "Atlas Web Studio",
        address: "12 Ibn Sina Ave",
        phone: "+212 655 230 876",
        city: "Tanger",
        country: "Morocco",
        client_type: "Company",
        currency: "MAD",
        siren: "543216789",
        vat: "MA654987321",
        ice: "0023456789002",
    },
    {
        user_id: "U-004",
        full_name: "Leila Bennis",
        email: "leila@brightpixel.com",
        company: "-",
        address: "78 Hassan II Blvd",
        phone: "+212 622 445 678",
        city: "Marrakech",
        country: "Morocco",
        client_type: "Individual",
        currency: "EUR",
        siren: "789654321",
        vat: "MA321654987",
        ice: "0078965432100",
    },
    {
        user_id: "U-005",
        full_name: "Omar Idrissi",
        email: "omar@cloudnest.com",
        company: "CloudNest",
        address: "5 Route de Fès",
        phone: "+212 677 110 998",
        city: "Fès",
        country: "Morocco",
        client_type: "Company",
        currency: "MAD",
        siren: "112233445",
        vat: "MA556677889",
        ice: "0011223344001",
    },
    {
        user_id: "U-006",
        full_name: "Mouna Chakir",
        email: "mouna@neosoft.com",
        company: "-",
        address: "26 Ocean Road",
        phone: "+212 633 900 221",
        city: "Agadir",
        country: "Morocco",
        client_type: "Individual",
        currency: "USD",
        siren: "998877665",
        vat: "MA443322110",
        ice: "0065544332211",
    },
    {
        user_id: "U-007",
        full_name: "Khalid Mansouri",
        email: "khalid@codecraft.com",
        company: "CodeCraft",
        address: "14 Massira St",
        phone: "+212 602 333 444",
        city: "Oujda",
        country: "Morocco",
        client_type: "Company",
        currency: "MAD",
        siren: "667788990",
        vat: "MA111223344",
        ice: "0077889900112",
    },
    {
        user_id: "U-008",
        full_name: "Nadia Rahimi",
        email: "nadia@pixelcore.com",
        company: "-",
        address: "91 Corniche Hassan II",
        phone: "+212 688 550 990",
        city: "Casablanca",
        country: "Morocco",
        client_type: "Individual",
        currency: "EUR",
        siren: "334455667",
        vat: "MA778899001",
        ice: "0044556677889",
    },
    {
        user_id: "U-009",
        full_name: "Hassan Fikri",
        email: "hassan@designflow.com",
        company: "DesignFlow",
        address: "8 Mohammed V Blvd",
        phone: "+212 611 234 567",
        city: "Kenitra",
        country: "Morocco",
        client_type: "Company",
        currency: "MAD",
        siren: "223344556",
        vat: "MA665544332",
        ice: "0088997766554",
    },
    {
        user_id: "U-010",
        full_name: "Fatima Zahra El Amrani",
        email: "fatima@nextgenmedia.com",
        company: "null Media",
        address: "100 Andalus St",
        phone: "+212 644 888 555",
        city: "Tetouan",
        country: "Morocco",
        client_type: "Individual",
        currency: "USD",
        siren: "556677889",
        vat: "MA998877665",
        ice: "0099008877665",
    },
];

export const TheActivityLogs = [
    {
        id: 1,
        created_at: "2025-04-05T14:22:10",
        user: { name: "Ahmed El", email: "ahmed@company.com" },
        action: "updated",
        table_name: "offers",
        record_id: 87,
        changes: {
            title: { old: "Ramadan Flash Sale", new: "Ramadan Mega Deal – 70% OFF" },
            discount_value: { old: "50", new: "70" },
            end_date: { old: "2025-04-10", new: "2025-04-20" },
        },
        ip_country: "MA",
        device: "Mobile",
    },
    {
        id: 2,
        created_at: "2025-04-05T13:05:33",
        user: { name: "Sara M.", email: "sara@company.com" },
        action: "created",
        table_name: "offers",
        record_id: 88,
        changes: {
            title: "Eid Al-Fitr Special",
            discount_value: "60",
            status: "active",
        },
        ip_country: "FR",
        device: "Desktop",
    },
    {
        id: 3,
        created_at: "2025-04-05T11:47:12",
        user: { name: "Youssef K.", email: "youssef@company.com" },
        action: "updated",
        table_name: "users",
        record_id: 156,
        changes: {
            role: { old: "staff", new: "manager" },
            status: { old: "inactive", new: "active" },
        },
        ip_country: "MA",
        device: "Mobile",
    },
    {
        id: 4,
        created_at: "2025-04-05T10:30:00",
        user: { name: "System", email: "auto@system.com" },
        action: "deleted",
        table_name: "offers",
        record_id: 79,
        changes: { title: "Expired Winter Promo 2024" },
        ip_country: "XX",
        device: "Server",
    },
    {
        id: 5,
        created_at: "2025-04-05T09:12:45",
        user: { name: "Fatima Z.", email: "fatima@company.com" },
        action: "created",
        table_name: "services",
        record_id: 22,
        changes: {
            name: "Premium Support Package",
            price: "299 MAD/month",
        },
        ip_country: "MA",
        device: "Desktop",
    },
    {
        id: 6,
        created_at: "2025-04-04T22:18:05",
        user: { name: "Omar R.", email: "omar@company.com" },
        action: "updated",
        table_name: "offers",
        record_id: 85,
        changes: {
            status: { old: "draft", new: "active" },
        },
        ip_country: "ES",
        device: "Mobile",
    },
    {
        id: 7,
        created_at: "2025-04-04T19:55:20",
        user: { name: "Admin", email: "admin@company.com" },
        action: "updated",
        table_name: "settings",
        record_id: 1,
        changes: {
            site_name: { old: "MyStore", new: "MegaDeals Morocco" },
            maintenance_mode: { old: "false", new: "true" },
        },
        ip_country: "MA",
        device: "Desktop",
    },
    {
        id: 8,
        created_at: "2025-04-04T16:40:11",
        user: { name: "Khadija L.", email: "khadija@company.com" },
        action: "created",
        table_name: "offers",
        record_id: 89,
        changes: {
            title: "Back to School 2025",
            discount_value: "40",
            start_date: "2025-09-01",
        },
        ip_country: "MA",
        device: "Tablet",
    },
    {
        id: 9,
        created_at: "2025-04-04T14:22:59",
        user: { name: "Nadia T.", email: "nadia@company.com" },
        action: "deleted",
        table_name: "offers",
        record_id: 72,
        changes: { title: "Duplicate Offer – Removed" },
        ip_country: "MA",
        device: "Mobile",
    },
    {
        id: 10,
        created_at: "2025-04-04T12:10:30",
        user: { name: "Mohamed A.", email: "mohamed@company.com" },
        action: "updated",
        table_name: "users",
        record_id: 203,
        changes: {
            email: { old: "old@email.com", new: "mohamed.new@company.com" },
        },
        ip_country: "DE",
        device: "Desktop",
    },
    {
        id: 11,
        created_at: "2025-04-03T23:59:59",
        user: { name: "System", email: "auto@system.com" },
        action: "updated",
        table_name: "offers",
        record_id: 81,
        changes: {
            status: { old: "active", new: "expired" },
        },
        ip_country: "XX",
        device: "Server",
    },
    {
        id: 12,
        created_at: "2025-04-03T18:44:22",
        user: { name: "Amina B.", email: "amina@company.com" },
        action: "created",
        table_name: "offers",
        record_id: 90,
        changes: {
            title: "Summer Collection Preview",
            discount_value: "30",
        },
        ip_country: "MA",
        device: "Mobile",
    },
    {
        id: 13,
        created_at: "2025-04-03T15:20:05",
        user: { name: "Karim S.", email: "karim@company.com" },
        action: "updated",
        table_name: "services",
        record_id: 19,
        changes: {
            price: { old: "199", new: "249" },
            description: { old: "Basic plan", new: "Pro plan with analytics included" },
        },
        ip_country: "CA",
        device: "Desktop",
    },
    {
        id: 14,
        created_at: "2025-04-03T11:11:11",
        user: { name: "System", email: "auto@system.com" },
        action: "created",
        table_name: "offers",
        record_id: 91,
        changes: {
            title: "Auto-generated Weekly Deal",
            discount_value: "25",
        },
        ip_country: "XX",
        device: "Server",
    },
    {
        id: 15,
        created_at: "2025-04-02T20:30:00",
        user: { name: "Laila H.", email: "laila@company.com" },
        action: "updated",
        table_name: "offers",
        record_id: 86,
        changes: {
            title: { old: "Flash Sale", new: "24H Flash Sale – Limited!" },
        },
        ip_country: "MA",
        device: "Mobile",
    },
    {
        id: 16,
        created_at: "2025-04-02T17:15:40",
        user: { name: "Reda F.", email: "reda@company.com" },
        action: "deleted",
        table_name: "services",
        record_id: 15,
        changes: { name: "Legacy Support Tier" },
        ip_country: "BE",
        device: "Desktop",
    },
    {
        id: 17,
        created_at: "2025-04-02T14:00:22",
        user: { name: "Zineb Q.", email: "zineb@company.com" },
        action: "created",
        table_name: "users",
        record_id: 211,
        changes: {
            name: "Zineb Q.",
            role: "staff",
            status: "active",
        },
        ip_country: "MA",
        device: "Mobile",
    },
    {
        id: 18,
        created_at: "2025-04-01T09:05:55",
        user: { name: "Hicham P.", email: "hicham@company.com" },
        action: "updated",
        table_name: "offers",
        record_id: 84,
        changes: {
            discount_type: { old: "percent", new: "fixed" },
            discount_value: { old: "40", new: "200" },
        },
        ip_country: "MA",
        device: "Desktop",
    },
    {
        id: 19,
        created_at: "2025-03-31T21:33:12",
        user: { name: "Imane D.", email: "imane@company.com" },
        action: "created",
        table_name: "offers",
        record_id: 92,
        changes: {
            title: "New Year 2026 Pre-Sale",
            discount_value: "55",
        },
        ip_country: "MA",
        device: "Mobile",
    },
    {
        id: 20,
        created_at: "2025-03-30T12:12:12",
        user: { name: "System", email: "auto@system.com" },
        action: "updated",
        table_name: "settings",
        record_id: 1,
        changes: {
            maintenance_mode: { old: "true", new: "false" },
        },
        ip_country: "XX",
        device: "Server",
    },
];